### ISSUE TITLE
Segfault when running unit tests.

### ISSUE THREAD

**Issue by siddsach** [allenai/bilm-tf#110]
`(.env) sidsachdeva@ip-10-0-4-107:~/bilm-tf$ python3 -m unittest discover tests/
.Found 1 shards at /tmp/tmp1d66o8v_
Loading data from: /tmp/tmp1d66o8v_
Loaded 3 sentences.
Finished loading
Found 1 shards at /tmp/tmp1d66o8v_
Loading data from: /tmp/tmp1d66o8v_
Loaded 3 sentences.
Finished loading
Loading data from: /tmp/tmp1d66o8v_
Loaded 3 sentences.
Finished loading
Loading data from: /tmp/tmp1d66o8v_
Loaded 3 sentences.
Finished loading
Found 1 shards at /tmp/tmp1d66o8v_
Loading data from: /tmp/tmp1d66o8v_
Loaded 3 sentences.
Finished loading
Found 1 shards at /tmp/tmp1d66o8v_
Loading data from: /tmp/tmp1d66o8v_
Loaded 3 sentences.
Finished loading
Loading data from: /tmp/tmp1d66o8v_
Loaded 3 sentences.
Finished loading
Loading data from: /tmp/tmp1d66o8v_
Loaded 3 sentences.
Finished loading
Found 1 shards at /tmp/tmp1d66o8v_
Loading data from: /tmp/tmp1d66o8v_
Loaded 3 sentences.
Finished loading
Found 1 shards at /tmp/tmp1d66o8v_
Loading data from: /tmp/tmp1d66o8v_
Loaded 3 sentences.
Finished loading
Loading data from: /tmp/tmp1d66o8v_
Loaded 3 sentences.
Finished loading
Loading data from: /tmp/tmp1d66o8v_
Loaded 3 sentences.
Finished loading
Found 1 shards at /tmp/tmp1d66o8v_
Loading data from: /tmp/tmp1d66o8v_
Loaded 3 sentences.
Finished loading
Found 1 shards at /tmp/tmp1d66o8v_
Loading data from: /tmp/tmp1d66o8v_
Loaded 3 sentences.
Finished loading
Loading data from: /tmp/tmp1d66o8v_
Loaded 3 sentences.
Finished loading
Loading data from: /tmp/tmp1d66o8v_
Loaded 3 sentences.
Finished loading
.Found 1 shards at /tmp/tmp6yqjkal7
Loading data from: /tmp/tmp6yqjkal7
Loaded 3 sentences.
Finished loading
Loading data from: /tmp/tmp6yqjkal7
Loaded 3 sentences.
Finished loading
.Found 1 shards at /tmp/tmpgqnbg2pu
Loading data from: /tmp/tmpgqnbg2pu
Loaded 3 sentences.
Finished loading
Loading data from: /tmp/tmpgqnbg2pu
Loaded 3 sentences.
Finished loading
.Found 1 shards at /tmp/tmpu7es9igw
Loading data from: /tmp/tmpu7es9igw
Loaded 3 sentences.
Finished loading
Loading data from: /tmp/tmpu7es9igw
Loaded 3 sentences.
Finished loading
.Found 1 shards at /tmp/tmprqu5hjzc
Loading data from: /tmp/tmprqu5hjzc
Loaded 3 sentences.
Finished loading
Loading data from: /tmp/tmprqu5hjzc
Loaded 3 sentences.
Finished loading
........2018-10-02 20:55:29.707411: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-10-02 20:55:29.796203: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-10-02 20:55:29.796619: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:1e.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2018-10-02 20:55:29.796654: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2018-10-02 20:55:30.109867: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-10-02 20:55:30.109930: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0
2018-10-02 20:55:30.109945: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N
2018-10-02 20:55:30.110228: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10757 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0, compute capability: 3.7)
WARNING:tensorflow:From /home/sidsachdeva/bilm-tf/bilm/model.py:384: calling squeeze (from tensorflow.python.ops.array_ops) with squeeze_dims is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
NOT USING SKIP CONNECTIONS
2018-10-02 20:55:32.631693: E tensorflow/stream_executor/cuda/cuda_dnn.cc:343] Loaded runtime CuDNN library: 7.1.4 but source was compiled with: 7.2.1.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
Segmentation fault (core dumped)
(.env) sidsachdeva@ip-10-0-4-107:`

Hey when I tried to run the tests described in the readme I get this segfault. I know this is probably way lower level of an issue than you guys would be responsible for, but I wonder if you might know how to fix it? Is it because of the difference in CuDNN library?

**Comment by matt-peters** [comment]
No idea what's causing this.  Check your version of tensorflow, the code is only tested with tensorflow==1.2.

**Comment by siddsach** [comment]
You're right, I had tensorflow-gpu==1.11.

However, now when I reinstalled the correct version and changed the, I'm getting a new error. 

`ImportError: Traceback (most recent call last):
  File "/home/sidsachdeva/bilm-tf/.env/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/sidsachdeva/bilm-tf/.env/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/sidsachdeva/bilm-tf/.env/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcudnn.so.5: cannot open shared object file: No such file or directory`

What CUDA version are you using? I have both 8.0 and 9.0 in my path, which are installed as standard in the Amazon Deep Learning AMI

**Comment by matt-peters** [comment]
I don't the CUDA version should matter, as long as it is one supported by the particular version of tensorflow.  It seems tensorflow can't find your CUDNN library, so this is an environmental issue. I'd recommend checking the typical environmental variables, `CUDA_HOME`, `LD_LIBRARY_PATH`, etc.

**Comment by siddsach** [comment]
Yeah so I checked those variables and they were configured as they should be. I found a fix in this issue thread: https://github.com/tensorflow/tensorflow/issues/8898 by using ln to create a link. Unfortunately that hasn't seemed to solve the segfault. I'm getting this error now when I run the tests. 

`........2018-10-03 00:02:42.547567: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-10-03 00:02:42.547611: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-10-03 00:02:42.547634: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-10-03 00:02:42.547657: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-10-03 00:02:42.547680: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2018-10-03 00:02:42.638421: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-10-03 00:02:42.638815: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties:
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:00:1e.0
Total memory: 11.17GiB
Free memory: 11.10GiB
2018-10-03 00:02:42.638853: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0
2018-10-03 00:02:42.638879: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y
2018-10-03 00:02:42.638914: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0)
/home/sidsachdeva/bilm-tf/.env/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py:499: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  return np.fromstring(tensor.tensor_content, dtype=dtype).reshape(shape)
NOT USING SKIP CONNECTIONS
/home/sidsachdeva/bilm-tf/.env/lib/python3.5/site-packages/tensorflow/python/util/tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
2018-10-03 00:02:45.133517: E tensorflow/stream_executor/cuda/cuda_dnn.cc:352] Loaded runtime CuDNN library: 7104 (compatibility version 7100) but source was compiled with 5110 (compatibility version 5100).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.
2018-10-03 00:02:45.134208: F tensorflow/core/kernels/conv_ops.cc:671] Check failed: stream->parent()->GetConvolveAlgorithms(&algorithms)
Aborted (core dumped)`

Though I'm able to load tensorflow and use the GPU, I'm not passing the tests for a specific reason. Any thoughts? Sorry for posting these annoying environment errors, I'm only using tf for this project because I want to train my own elmo, otherwise I usually use pytorch, where I almost never have such issues.

**Comment by matt-peters** [comment]
This could be a mismatch between your installed CUDA / CUDNN version and the one that tensorflow==1.2 expects.  The last few lines of your error message:

```Loaded runtime CuDNN library: 7104 (compatibility version 7100) but source was compiled with 5110 (compatibility version 5100). If using a binary install, upgrade your CuDNN library to match. If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration```

**Comment by siddsach** [comment]
I ended up fixing this by installing the tf-nightly build! Thanks for the help!
