### ISSUE TITLE
return list(zip(ids, chars_ids)) MemoryError

### ISSUE THREAD

**Issue by whaozl** [allenai/bilm-tf#118]
I loaded 20G text corpus, memory is 187G, but the corpus loading was successful, and prompting `memory error` in the `list(zip(ids, chars_ids))`

```
nohup: ignoring input
Found 1 shards at /home/hotel_ai/haozl/elmo/seg_all.txt
Loading data from: /home/hotel_ai/haozl/elmo/seg_all.txt
Loaded 211905361 sentences.
Finished loading
Found 1 shards at /home/hotel_ai/haozl/elmo/seg_all.txt
Loading data from: /home/hotel_ai/haozl/elmo/seg_all.txt
Loaded 211905361 sentences.
Finished loading
Traceback (most recent call last):
  File "/home/hotel_ai/haozl/elmo/bilmtf/bin/train_elmo.py", line 81, in <module>
    main(args)
  File "/home/hotel_ai/haozl/elmo/bilmtf/bin/train_elmo.py", line 67, in main
    shuffle_on_load=True)
  File "/home/hotel_ai/haozl/elmo/bilmtf/bilm/data.py", line 445, in __init__
    shuffle_on_load=shuffle_on_load)
  File "/home/hotel_ai/haozl/elmo/bilmtf/bilm/data.py", line 342, in __init__
    self._ids = self._load_random_shard()
  File "/home/hotel_ai/haozl/elmo/bilmtf/bilm/data.py", line 365, in _load_random_shard
    ids = self._load_shard(shard_name)
  File "/home/hotel_ai/haozl/elmo/bilmtf/bilm/data.py", line 405, in _load_shard
    return list(zip(ids, chars_ids))
MemoryError
```

**Comment by matt-peters** [comment]
Split your dataset into several different files as the training code only loads two files at a time. 
 Loading 212 M sentences at once will run out of memory as the raw text is converted to character id arrays and consequently occupies far more memory then the raw text.

**Comment by whaozl** [comment]
when the trianing, only loads two files at a time? and

Can we load all the separate corpora by the method it provides step by step?
