### ISSUE TITLE
error when i unittest tests

### ISSUE THREAD

**Issue by NLP-konic** [allenai/bilm-tf#119]
when i  use  command line for windows  on"python -m unittest  discover tests/",it's run a error:

OSError: [WinError 145] 目录不是空的。: 'C:\\Users\\WXS-10~1\\AppData\\Local\\Temp\\tmpb_9y0pt2'

======================================================================
ERROR: test_train_bilm_chars (test_training.TestLanguageModel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\wxs-1080TI\Downloads\bilm-tf-master\tests\test_training.py", line 93, in test_train_bilm_chars
    train(options, data, 1, self.tmp_dir, self.tmp_dir)
  File "C:\Users\wxs-1080TI\Downloads\bilm-tf-master\bilm\training.py", line 686, in train
    initializer=tf.constant_initializer(0), trainable=False)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1467, in get_variable
    aggregation=aggregation)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1217, in get_variable
    aggregation=aggregation)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 527, in get_variable
    aggregation=aggregation)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 481, in _true_getter
    aggregation=aggregation)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 848, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable global_step already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3155, in create_op
    op_def=op_def)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\util\deprecation.py", line 454, in new_func
    return func(*args, **kwargs)

======================================================================
ERROR: test_train_bilm_chars (test_training.TestLanguageModel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\wxs-1080TI\Downloads\bilm-tf-master\tests\test_training.py", line 20, in tearDown
    os.remove(self.tmp_file)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\WXS-10~1\\AppData\\Local\\Temp\\tmpcp2_usue'

======================================================================
ERROR: test_train_shared_softmax_embedding (test_training.TestLanguageModel)

it said the directory  is  not empty and another programming is  using this file ,so the process  can't  access 。
the error occured on the  test_training.py at 20 line:
class TestLanguageModel(unittest.TestCase):
    def tearDown(self):
        shutil.rmtree(self.tmp_dir)
        os.remove(self.tmp_file)    # the error  
        tf.reset_default_graph()

**Comment by matt-peters** [comment]
We haven't tried to support windows, so won't be of any help in diagnosing this.
