### ISSUE TITLE
*question* I'm in trouble with dimension matching after runing several steps in implement experiments .

### ISSUE THREAD

**Issue by XiaoqingNLP** [allenai/bilm-tf#122]
##### problem
my program will report a error with dimension dismatch in the dynamic_rnn concat.
##### try
 I have searching using google.com and baidu.com and someone said it is due to the batch size , Moreover, I have try to fix the batch size ,the problem not solved.
##### some useful information
I use the Elmo in transformer and transformer is using the number of tokens as the batch_size is different with the number of sentences as the batch_size
##### log

> INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:loss = 9.223154, step = 1, target = [624  40], source = [624  40]
INFO:tensorflow:Saving checkpoints for 2 into train/model.ckpt.
INFO:tensorflow:loss = 9.222191, step = 2, target = [520  48], source = [520  48] (72.819 sec)
INFO:tensorflow:loss = 9.21151, step = 3, target = [440  56], source = [440  56] (2.161 sec)
INFO:tensorflow:loss = 9.160345, step = 4, target = [776  32], source = [776  32] (2.003 sec)
INFO:tensorflow:loss = 9.169487, step = 5, target = [624  40], source = [624  40] (2.115 sec)
INFO:tensorflow:loss = 9.171974, step = 6, target = [312  80], source = [312  80] (2.577 sec)
INFO:tensorflow:loss = 9.098288, step = 7, target = [888  28], source = [888  28] (1.905 sec)
Traceback (most recent call last):
  File "./code/trainer.py", line 494, in <module>
    main(parse_args())
  File "./code/trainer.py", line 479, in main
    sess._tf_sess().run(ops["collect_op"])
  File "/home/xqzhou/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/xqzhou/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/xqzhou/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/xqzhou/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [130,512] vs. shape[1] = [128,512]
	 [[Node: parallel_1/transformer/Encoder_elmo/bilm/RNN_0/RNN/MultiRNNCell/Cell0/rnn/while/lstm_cell/concat = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32,
 _class=["loc:@creat...rayWriteV3"], _device="/job:localhost/replica:0/task:0/device:GPU:1"](parallel_1/transformer/Encoder_elmo/bilm/RNN_0/RNN/MultiRNNCell/Cell0/rnn/while/TensorArrayReadV3, parallel_1/transformer/Encoder_elmo/bilm/RNN_0/RNN/MultiRNNCell/Cell0/rnn/while/Switch_4:1, parallel_1/transformer/Encoder_elmo/bilm/RNN_0/RNN/MultiRNNCell/Cell0/rnn/while/lstm_cell/split/split_dim)]]	 [[Node: parallel_2/transformer/Encoder_elmo/bilm/RNN_1/RNN/MultiRNNCell/Cell1/rnn/stack/_6251 = _Recv[client_terminated=false, recv_device="/job:lo
calhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:2", send_device_incarnation=1, tensor_name="edge_7494_.../rnn/stack", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Caused by op u'parallel_1/transformer/Encoder_elmo/bilm/RNN_0/RNN/MultiRNNCell/Cell0/rnn/while/lstm_cell/concat', defined at:
  File "./code/trainer.py", line 494, in <module>
    main(parse_args())
  File "./code/trainer.py", line 362, in main
    params.device_list
  File "/data1/xqzhou/e27d-thumt/wmt17-deen-dir/elmo-dir/baseline/code/thumt/utils/parallel.py", line 130, in parallel_model
    outputs = data_parallelism(devices, model_fn, features)
  File "/data1/xqzhou/e27d-thumt/wmt17-deen-dir/elmo-dir/baseline/code/thumt/utils/parallel.py", line 86, in data_parallelism
    outputs.append(fns[i](*new_args[i], **new_kwargs[i]))
  File "/data1/xqzhou/e27d-thumt/wmt17-deen-dir/elmo-dir/baseline/code/thumt/models/transformer.py", line 385, in training_fn
    loss = model_graph(features, "train", params)
  File "/data1/xqzhou/e27d-thumt/wmt17-deen-dir/elmo-dir/baseline/code/thumt/models/transformer.py", line 362, in model_graph
    encoder_output = encoding_graph(features, mode, params)
  File "/data1/xqzhou/e27d-thumt/wmt17-deen-dir/elmo-dir/baseline/code/thumt/models/transformer.py", line 202, in encoding_graph
    src_seq_embeddings_op = bilm(src_seq)
  File "/data1/xqzhou/e27d-thumt/wmt17-deen-dir/elmo-dir/baseline/code/bilm/model.py", line 104, in __call__
    max_batch_size=self._max_batch_size)
  File "/data1/xqzhou/e27d-thumt/wmt17-deen-dir/elmo-dir/baseline/code/bilm/model.py", line 296, in __init__
    self._build()
  File "/data1/xqzhou/e27d-thumt/wmt17-deen-dir/elmo-dir/baseline/code/bilm/model.py", line 303, in _build
    self._build_lstms()
  File "/data1/xqzhou/e27d-thumt/wmt17-deen-dir/elmo-dir/baseline/code/bilm/model.py", line 587, in _build_lstms
    *batch_init_states),
  File "/home/xqzhou/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 627, in dynamic_rnn
    dtype=dtype)
  File "/home/xqzhou/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 824, in _dynamic_rnn_loop
    swap_memory=swap_memory)
  File "/home/xqzhou/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3224, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/xqzhou/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2956, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/xqzhou/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2893, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/xqzhou/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3194, in <lambda>
    body = lambda i, lv: (i + 1, orig_body(*lv))
  File "/home/xqzhou/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 793, in _time_step
    skip_conditionals=True)
  File "/home/xqzhou/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 248, in _rnn_step
    new_output, new_state = call_cell()
  File "/home/xqzhou/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 781, in <lambda>
    call_cell = lambda: cell(input_t, state)
  File "/home/xqzhou/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 339, in __call__
    *args, **kwargs)
  File "/home/xqzhou/anaconda2/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 717, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/xqzhou/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 833, in call
    array_ops.concat([inputs, m_prev], 1), self._kernel)
  File "/home/xqzhou/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1189, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "/home/xqzhou/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 953, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "/home/xqzhou/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/xqzhou/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/xqzhou/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): ConcatOp : Dimensions of inputs should match: shape[0] = [130,512] vs. shape[1] = [128,512]
	 [[Node: parallel_1/transformer/Encoder_elmo/bilm/RNN_0/RNN/MultiRNNCell/Cell0/rnn/while/lstm_cell/concat = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32,
 _class=["loc:@creat...rayWriteV3"], _device="/job:localhost/replica:0/task:0/device:GPU:1"](parallel_1/transformer/Encoder_elmo/bilm/RNN_0/RNN/MultiRNNCell/Cell0/rnn/while/TensorArrayReadV3, parallel_1/transformer/Encoder_elmo/bilm/RNN_0/RNN/MultiRNNCell/Cell0/rnn/while/Switch_4:1, parallel_1/transformer/Encoder_elmo/bilm/RNN_0/RNN/MultiRNNCell/Cell0/rnn/while/lstm_cell/split/split_dim)]]	 [[Node: parallel_2/transformer/Encoder_elmo/bilm/RNN_1/RNN/MultiRNNCell/Cell1/rnn/stack/_6251 = _Recv[client_terminated=false, recv_device="/job:lo
calhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:2", send_device_incarnation=1, tensor_name="edge_7494_.../rnn/stack", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by vishal2612200** [comment]
@PlayDeep How does you solve this problem? Can you please write a way to solve this problem.
