### ISSUE TITLE
OOM when run_test but not training/predicting

### ISSUE THREAD

**Issue by tcqiuyu** [allenai/bilm-tf#127]
I've seen OOM issues. My issue is similar to #53. OOM occurs when allocating for tensor shaped [5120,891169]. See below..

> totalMemory: 22.38GiB freeMemory: 21.57GiB
> 2018-11-06 20:59:55.514217: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had neg
> ative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2018-11-06 20:59:55.514974: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 1 with properties:
> name: Tesla P40 major: 6 minor: 1 memoryClockRate(GHz): 1.531
> pciBusID: 0000:84:00.0
> totalMemory: 22.38GiB freeMemory: 21.57GiB
> 2018-11-06 20:59:55.515136: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Device peer to peer matrix
> 2018-11-06 20:59:55.515172: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1051] DMA: 0 1
> 2018-11-06 20:59:55.515181: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1061] 0:   Y Y
> 2018-11-06 20:59:55.515187: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1061] 1:   Y Y
> 2018-11-06 20:59:55.515199: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (
> device: 0, name: Tesla P40, pci bus id: 0000:83:00.0, compute capability: 6.1)
> 2018-11-06 20:59:55.515208: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:1) -> (
> device: 1, name: Tesla P40, pci bus id: 0000:84:00.0, compute capability: 6.1)
> USING SKIP CONNECTIONS

...

> Limit:                 21999848653
> InUse:                  2229972480
> MaxInUse:               8623861760
> NumAllocs:                    1244
> MaxAllocSize:           2214690816
> 
> 2018-11-06 21:00:13.184382: W tensorflow/core/common_runtime/bfc_allocator.cc:277] ****_______________**********____________________
> ___________________________________________________
> 2018-11-06 21:00:13.184404: W tensorflow/core/framework/op_kernel.cc:1192] Resource exhausted: OOM when allocating tensor with shape
> [5120,891169]
> Traceback (most recent call last):
>   File "/ada/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
>     return fn(*args)
>   File "/ada/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
>     status, run_metadata)
>   File "/ada/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
>     c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[5120,891169]
>          [[Node: lm/MatMul_10 = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/de
> vice:GPU:0"](lm/Reshape_7, lm/transpose)]]
>          [[Node: lm/mul_8/_141 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_dev
> ice="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3795_lm/mul_8", tensor_type=DT_FLOA
> T, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
> 

But the model can run successfully on training and predicting. I wondered why run_test take more gpu memory usage. Any help would be appreciate. Thanks

**Comment by tcqiuyu** [comment]
I worked this out. It is because the test batch is greater than the training process. This issue can be closed. Thanks
