### ISSUE TITLE
Error Occured 

### ISSUE THREAD

**Issue by anupamjamatia** [allenai/bilm-tf#161]
I am getting while running the command 

> (keras-tf-env3-Elmo) anupam@anupam-OMEN-HP:~/Desktop/ElMo/bilm-tf-master$ python -m unittest discover tests/
.Found 1 shards at /tmp/tmpchp8e__6
Loading data from: /tmp/tmpchp8e__6
Loaded 3 sentences.
Finished loading
Found 1 shards at /tmp/tmpchp8e__6
Loading data from: /tmp/tmpchp8e__6
Loaded 3 sentences.
Finished loading
Loading data from: /tmp/tmpchp8e__6
Loaded 3 sentences.
Finished loading
Loading data from: /tmp/tmpchp8e__6
Loaded 3 sentences.
Finished loading
Found 1 shards at /tmp/tmpchp8e__6
Loading data from: /tmp/tmpchp8e__6
Loaded 3 sentences.
Finished loading
Found 1 shards at /tmp/tmpchp8e__6
Loading data from: /tmp/tmpchp8e__6
Loaded 3 sentences.
Finished loading
Loading data from: /tmp/tmpchp8e__6
Loaded 3 sentences.
Finished loading
Loading data from: /tmp/tmpchp8e__6
Loaded 3 sentences.
Finished loading
Found 1 shards at /tmp/tmpchp8e__6
Loading data from: /tmp/tmpchp8e__6
Loaded 3 sentences.
Finished loading
Found 1 shards at /tmp/tmpchp8e__6
Loading data from: /tmp/tmpchp8e__6
Loaded 3 sentences.
Finished loading
Loading data from: /tmp/tmpchp8e__6
Loaded 3 sentences.
Finished loading
Loading data from: /tmp/tmpchp8e__6
Loaded 3 sentences.
Finished loading
Found 1 shards at /tmp/tmpchp8e__6
Loading data from: /tmp/tmpchp8e__6
Loaded 3 sentences.
Finished loading
Found 1 shards at /tmp/tmpchp8e__6
Loading data from: /tmp/tmpchp8e__6
Loaded 3 sentences.
Finished loading
Loading data from: /tmp/tmpchp8e__6
Loaded 3 sentences.
Finished loading
Loading data from: /tmp/tmpchp8e__6
Loaded 3 sentences.
Finished loading
.Found 1 shards at /tmp/tmp55a5llby
Loading data from: /tmp/tmp55a5llby
Loaded 3 sentences.
Finished loading
Loading data from: /tmp/tmp55a5llby
Loaded 3 sentences.
Finished loading
.Found 1 shards at /tmp/tmpa9apd0fs
Loading data from: /tmp/tmpa9apd0fs
Loaded 3 sentences.
Finished loading
Loading data from: /tmp/tmpa9apd0fs
Loaded 3 sentences.
Finished loading
.Found 1 shards at /tmp/tmp19huk5ds
Loading data from: /tmp/tmp19huk5ds
Loaded 3 sentences.
Finished loading
Loading data from: /tmp/tmp19huk5ds
Loaded 3 sentences.
Finished loading
.Found 1 shards at /tmp/tmpgzf2npaf
Loading data from: /tmp/tmpgzf2npaf
Loaded 3 sentences.
Finished loading
Loading data from: /tmp/tmpgzf2npaf
Loaded 3 sentences.
Finished loading
........EEEEEE
======================================================================
ERROR: test_weighted_layers (test_elmo.TestWeightedLayers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/anupam/Desktop/ElMo/bilm-tf-master/tests/test_elmo.py", line 23, in setUp
    self.sess = tf.Session()
AttributeError: module 'tensorflow' has no attribute 'Session'

======================================================================
ERROR: test_weighted_layers_no_norm (test_elmo.TestWeightedLayers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/anupam/Desktop/ElMo/bilm-tf-master/tests/test_elmo.py", line 23, in setUp
    self.sess = tf.Session()
AttributeError: module 'tensorflow' has no attribute 'Session'

======================================================================
ERROR: test_weighted_layers_top_only (test_elmo.TestWeightedLayers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/anupam/Desktop/ElMo/bilm-tf-master/tests/test_elmo.py", line 23, in setUp
    self.sess = tf.Session()
AttributeError: module 'tensorflow' has no attribute 'Session'

======================================================================
ERROR: test_bilm (test_model.TestBidirectionalLanguageModel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/anupam/Desktop/ElMo/bilm-tf-master/tests/test_model.py", line 45, in setUp
    self.sess = tf.Session()
AttributeError: module 'tensorflow' has no attribute 'Session'

======================================================================
ERROR: test_bilm_token (test_model.TestBidirectionalLanguageModelTokenInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/anupam/Desktop/ElMo/bilm-tf-master/tests/test_model.py", line 135, in setUp
    self.sess = tf.Session()
AttributeError: module 'tensorflow' has no attribute 'Session'

======================================================================
ERROR: test_training (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_training
Traceback (most recent call last):
  File "/home/anupam/anaconda3/envs/keras-tf-env3-Elmo/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/anupam/anaconda3/envs/keras-tf-env3-Elmo/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/anupam/Desktop/ElMo/bilm-tf-master/tests/test_training.py", line 11, in <module>
    from bilm.training import train, test, load_vocab, \
  File "/home/anupam/Desktop/ElMo/bilm-tf-master/bilm/training.py", line 13, in <module>
    from tensorflow.python.ops.init_ops import glorot_uniform_initializer
ModuleNotFoundError: No module named 'tensorflow.python'

----------------------------------------------------------------------
Ran 19 tests in 0.057s

Please some one help to cinfigure.

Regards

**Comment by matt-peters** [comment]
What version of tensorflow are you using?  This repo has only been tested up to version 1.2.

**Comment by anupamjamatia** [comment]
Hi Matt, I have used the exact instructions written in the GitHub.
https://pastebin.com/Z4bnGE56
May I know the software requirements to run the repo.

Thanks Regards

**Comment by anupamjamatia** [comment]
(keras-tf-env3Elmo) anupam@anupam-OMEN-HP:~/Desktop/ElMo/bilm-tf-master$ pip list
Package             Version   
------------------- ----------
backports.weakref   1.0rc1    
bleach              1.5.0     
certifi             2018.11.29
cycler              0.10.0    
h5py                2.9.0     
html5lib            0.9999999 
Keras               2.2.4     
Keras-Applications  1.0.6     
Keras-Preprocessing 1.0.5     
kiwisolver          1.0.1     
Markdown            2.2.0     
matplotlib          3.0.2     
mock                2.0.0     
numpy               1.16.0    
pbr                 5.1.1     
pip                 19.0.1    
protobuf            3.6.1     
pydot-ng            2.0.0     
pyparsing           2.3.1     
python-dateutil     2.7.5     
PyYAML              3.13      
scikit-learn        0.20.2    
scipy               1.2.0     
setuptools          40.6.3    
six                 1.12.0    
sklearn             0.0       
tensorflow-gpu      1.2.0     
Theano              1.0.3     
Werkzeug            0.14.1    
wheel               0.32.3    
(keras-tf-env3Elmo) anupam@anupam-OMEN-HP:~/Desktop/ElMo/bilm-tf-master$ 



These are the software installed in my python virtual environment.

**Comment by rianapriansyah** [comment]
In my case, the error occurred because my Cuda was not compatible with installed tensorflow which is 1.2.

So what I did to resolve the error was to check my Cuda version and reinstall Tensorflow using the version that compatible with Cuda. 
My setting was : 
Cuda 10.0
Tensorflow 1.5
