### ISSUE TITLE
OOM in CPU when training

### ISSUE THREAD

**Issue by pjox** [allenai/bilm-tf#174]
Hello,

I am currently training ELMo for the French language and I'm using a very similar setup to the one described in the original ELMo paper, namely:
> CPU: Intel(R) Xeon(R) Gold 5118 CPU @ 2.30GHz, 2 x 12 cores. Memory: 128GB. GPU: 4 x Nvidia GeForce GTX 1080Ti [I'm using 3 of the 4 GPU's].

I have already trained one model successfully, but after adding more data I began to encounter the following error:

```text
2019-02-26 15:37:00.002412: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at cwise_ops_common.cc:70 : Resource exhausted: OOM when allocating tensor with shape[12857161,512] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
Traceback (most recent call last):
  File "/scratch/portizsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/scratch/portizsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/scratch/portizsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[12857161,512] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
	 [[{{node mul_112}} = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](lm/softmax/W/read, lm/softmax/W/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[{{node clip_by_global_norm/clip_by_global_norm/_4/_1757}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_83235_clip_by_global_norm/clip_by_global_norm/_4", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/train_elmo.py", line 73, in <module>
    main(args)
  File "bin/train_elmo.py", line 63, in main
    train(options, data, n_gpus, tf_save_dir, tf_log_dir)
  File "/scratch/portizsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/bilm-0.1.post5-py3.6.egg/bilm/training.py", line 876, in train
    feed_dict=feed_dict
  File "/scratch/portizsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/scratch/portizsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/scratch/portizsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/scratch/portizsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[12857161,512] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
	 [[node mul_112 (defined at /scratch/portizsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/bilm-0.1.post5-py3.6.egg/bilm/training.py:620)  = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](lm/softmax/W/read, lm/softmax/W/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[{{node clip_by_global_norm/clip_by_global_norm/_4/_1757}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_83235_clip_by_global_norm/clip_by_global_norm/_4", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


Caused by op 'mul_112', defined at:
  File "bin/train_elmo.py", line 73, in <module>
    main(args)
  File "bin/train_elmo.py", line 63, in main
    train(options, data, n_gpus, tf_save_dir, tf_log_dir)
  File "/scratch/portizsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/bilm-0.1.post5-py3.6.egg/bilm/training.py", line 753, in train
    summary_gradient_updates(grads, opt, lr))
  File "/scratch/portizsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/bilm-0.1.post5-py3.6.egg/bilm/training.py", line 620, in summary_gradient_updates
    values_norm = tf.sqrt(tf.reduce_sum(v * v)) + 1.0e-7
  File "/scratch/portizsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 856, in _run_op
    return getattr(ops.Tensor, operator)(a._AsTensor(), *args)
  File "/scratch/portizsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 878, in binary_op_wrapper
    return func(x, y, name=name)
  File "/scratch/portizsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1131, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "/scratch/portizsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 5042, in mul
    "Mul", x=x, y=y, name=name)
  File "/scratch/portizsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/scratch/portizsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/scratch/portizsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/scratch/portizsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[12857161,512] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
	 [[node mul_112 (defined at /scratch/portizsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/bilm-0.1.post5-py3.6.egg/bilm/training.py:620)  = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](lm/softmax/W/read, lm/softmax/W/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[{{node clip_by_global_norm/clip_by_global_norm/_4/_1757}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_83235_clip_by_global_norm/clip_by_global_norm/_4", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
```
Could this be a problem with the data? I am segmenting the training data into files of at most 30MB... Do I need more than 128 GB of RAM to train ELMo? Is it normal that the CPU memory runs out but not the GPU memory?

Thank you in advance.

**Comment by PhilipMay** [comment]
I had such an OOM error when my dictionary was too large. I had to limit it to the top 800,000 entries. Maybe you should try this.

**Comment by pjox** [comment]
Just to be sure, when you say dictionary, do you mean the vocabulary file? Should it be shorter than 800,000 tokens?

**Comment by PhilipMay** [comment]
> Just to be sure, when you say dictionary, do you mean the vocabulary file? Should it be shorter than 800,000 tokens?

Yes exactly. Sorry for the confusion.

**Comment by PhilipMay** [comment]
See here: https://github.com/PhilipMay/de-wiki-text-corpus-tools/blob/master/vocab_file_writer.py

**Comment by pjox** [comment]
Ok, thanks! I'll try with a smaller vocabulary. 😄 (And thank you for the script)

**Comment by DomHudson** [comment]
Thanks for this Philip. For reference: the original training data (for all models except the largest 5.5B) has a vocabulary size of 793471 (including `<S>`, `</S>`, `<UNK>`). This vocabulary was built by discarding all words with a count below 3.
