### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by yslin1995** [allenai/bilm-tf#177]
Hi, I have trouble training ELMO on my own Twitter corpus. When running train_elmo.py, an error occurred and it said "TypeError: 'NoneType' object is not subscriptable", so I tried to print X, and all I got were listed below. 

> Training for 10 epochs and 496090 batches
> {'token_ids': array([[    0,     3,   204, ..., 41070,     9,   381],
>        [    0,   383,    19, ...,     3,     7,   209],
>        [    0,    99,    10, ...,    55,     3,     0],
>        ...,
>        [    0,    96,   210, ...,     6,     4,     5],
>        [    0,     4,     0, ...,    15,   626,   125],
>        [    0,    12,     3, ...,  1443,  3054,  4734]], dtype=int32), 'tokens_characters': None, 'next_token_id': array([[    3,   204,   139, ...,     9,   381,    30],
>        [  383,    19,    67, ...,     7,   209,   227],
>        [   99,    10, 29181, ...,     3,     1,   114],
>        ...,
>        [   96,   210,   604, ...,     4,     5,     5],
>        [    4,     1,   574, ...,   626,   125,    65],
>        [   12,     3,     7, ...,  3054,  4734,    16]], dtype=int32), 'token_ids_reverse': array([[     1,      5,      3, ...,     11,   2053,     11],
>        [     1,      5,      3, ...,      1,     26,   6456],
>        [     1,     23,   1035, ...,     18,   9856,    498],
>        ...,
>        [     1,   3602,    369, ...,     58,   1759,   1620],
>        [     1,      4,      4, ...,      6,  12178,     13],
>        [     1, 128831,    143, ...,      6,   2702,     57]], dtype=int32), 'tokens_characters_reverse': None, 'next_token_id_reverse': array([[     5,      3,    216, ...,   2053,     11,   2971],
>        [     5,      3,      4, ...,     26,   6456,     57],
>        [    23,   1035,     47, ...,   9856,    498,  14783],
>        ...,
>        [  3602,    369,   6770, ...,   1759,   1620,    290],
>        [     4,      4,      3, ...,  12178,     13,     35],
>        [128831,    143,    280, ...,   2702,     57,     69]], dtype=int32)}
> Traceback (most recent call last):
>   File "bin/train_elmo.py", line 72, in <module>
>     main(args)
>   File "bin/train_elmo.py", line 62, in main
>     train(options, data, n_gpus, tf_save_dir, tf_log_dir)
>   File "/home/yslin/code/tweet/bilm-tf/bin/bilm/training.py", line 852, in train
>     char_inputs, bidirectional)
>   File "/home/yslin/code/tweet/bilm-tf/bin/bilm/training.py", line 653, in _get_feed_dict_from_X
>     char_ids = X['tokens_characters'][start:end]
> TypeError: 'NoneType' object is not subscriptable
> 

I wonder if it is because my X is composed of any words that can not be split into characters, making the attribute <tokens_characters> NoneType, so I tried a file with only english words, but the bug is still there. 

Thanks in advance.

**Comment by yslin1995** [comment]
Solved, it was caused by the 'max_word_length' set to None...
