### ISSUE TITLE
Not able to start training

### ISSUE THREAD

**Issue by 008karan** [allenai/bilm-tf#180]
`Traceback (most recent call last):
  File "bin/train_elmo.py", line 6, in <module>
    from bilm.training import train, load_options_latest_checkpoint, load_vocab
  File "/home/gamut/Downloads/bilm-tf-master/bin/bilm/__init__.py", line 2, in <module>
    from .data import Batcher, TokenBatcher
  File "/home/gamut/Downloads/bilm-tf-master/bin/bilm/data.py", line 197
    def __init__(self, lm_vocab_file: str, max_token_length: int):
SyntaxError: invalid syntax
`

**Comment by huhuigou** [comment]
have you  solved  the problem?

**Comment by 008karan** [comment]
Yes. It was issue of cudnn version mismatch with TensorFlow.
