### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by 2hip3ng** [allenai/bilm-tf#188]
when training the 1-B model fllowing the README.md

**Comment by akashchaudhari98** [comment]
how was this solved ??getting same error 

(elmo_train) D:\bilm-tf-master\bilm-tf-master>python D:/bilm-tf-master/bilm-tf-master/bin/train_elmo.py --train_prefix='D:/Dataset/swb/swb/train/*' --vocab_file D:/Dataset/swb/swb/vocab.txt --save_dir D:/Dataset/swb/swb/checkpoint
2020-03-14 13:12:12.730859: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
WARNING:tensorflow:From D:\bilm-tf-master\bilm-tf-master\bin\bilm\training.py:21: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From D:\bilm-tf-master\bilm-tf-master\bin\bilm\training.py:21: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

Found 0 shards at 'D:/Dataset/swb/swb/train/*'
Traceback (most recent call last):
  File "D:/bilm-tf-master/bilm-tf-master/bin/train_elmo.py", line 73, in <module>
    main(args)
  File "D:/bilm-tf-master/bilm-tf-master/bin/train_elmo.py", line 59, in main
    shuffle_on_load=True)
  File "D:\bilm-tf-master\bilm-tf-master\bin\bilm\data.py", line 442, in __init__
    shuffle_on_load=shuffle_on_load)
  File "D:\bilm-tf-master\bilm-tf-master\bin\bilm\data.py", line 342, in __init__
    self._ids = self._load_random_shard()
  File "D:\bilm-tf-master\bilm-tf-master\bin\bilm\data.py", line 363, in _load_random_shard
    shard_name = self._choose_random_shard()
  File "D:\bilm-tf-master\bilm-tf-master\bin\bilm\data.py", line 348, in _choose_random_shard
    shard_name = self._shards_to_choose.pop()
IndexError: pop from empty list
