### ISSUE TITLE
Cannot load elmo (trained on a new corpus) in allennlp

### ISSUE THREAD

**Issue by felixwzh** [allenai/bilm-tf#79]
Hi Matthew, thanks for your code.
I followed the [5-step Training a biLM on a new corpus](https://github.com/allenai/bilm-tf#training-a-bilm-on-a-new-corpus) and passed the first 4 steps. But in the last step, I had a problem when loading elmo trained on my own corpus using the code like [here (Using ELMo programmatically)](https://github.com/allenai/allennlp/blob/03d6fadbc4fcb61caa5980ab61d1ca673fc0922b/tutorials/how_to/elmo.md#using-elmo-programmatically)
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/allennlp/modules/elmo.py", line 99, in __init__
    vocab_to_cache=vocab_to_cache)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/modules/elmo.py", line 528, in __init__
    self._elmo_lstm.load_weights(weight_file)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/modules/elmo_lstm.py", line 299, in load_weights
    proj_weights = numpy.transpose(dataset['W_P_0'][...])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/group.py", line 177, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'W_P_0' doesn't exist)"
```
and the corresponding options.json I used for training and dumping is
```
{"bidirectional": true,
     "char_cnn": {"activation": "relu",
                  "embedding": {"dim": 16},
                  "filters": [[1, 32], [2, 16], [3, 16], [4, 128], [5, 128], [6, 256], [7, 256]],
                  "max_characters_per_token": 50,
                  "n_characters": 261,
                  "n_highway": 2},
     "dropout": 0.1,
     "lstm": {"cell_clip": 3,
              "dim": 512, "n_layers": 2,
              "proj_clip": 3,
              "projection_dim": 512,
              "use_skip_connections": true},
     "all_clip_norm_val": 10.0,
     "n_epochs": 40,
     "n_train_tokens": 23730468,
     "batch_size": 2,
     "n_tokens_vocab": 30000,
     "unroll_steps": 40,
     "n_negative_samples_batch": 128}
```
I don't know where should I add the `W_P_0` mentioned in the error.
How can I fix this? 

best,
Zhenghui

**Comment by felixwzh** [comment]
It seems that it works if I add `"projection_after_highway": true` in the options.
so now it is
```
{"bidirectional": true,
     "char_cnn": {"activation": "relu",
                  "embedding": {"dim": 16},
                  "projection_after_highway": true
                  "filters": [[1, 32], [2, 16], [3, 16], [4, 128], [5, 128], [6, 256], [7, 256]],
                  "max_characters_per_token": 50,
                  "n_characters": 261,
                  "n_highway": 2},
     "dropout": 0.1,
     "lstm": {"cell_clip": 3,
              "dim": 512, "n_layers": 2,
              "proj_clip": 3,
              "projection_dim": 512,
              "use_skip_connections": true},
     "all_clip_norm_val": 10.0,
     "n_epochs": 40,
     "n_train_tokens": 23730468,
     "batch_size": 2,
     "n_tokens_vocab": 30000,
     "unroll_steps": 40,
     "n_negative_samples_batch": 128}
```
Is this the correct solution?
I find this settings also in [options](https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway_tf_checkpoint/options.json) But this line (`projection_after_highway": true`) is now included explicitly in [train_elmo.py](https://github.com/allenai/bilm-tf/blob/master/bin/train_elmo.py), maybe it would be better to include it in [train_elmo.py](https://github.com/allenai/bilm-tf/blob/master/bin/train_elmo.py)？
